# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence


stages:
  - test
  - sectest

sast:
  stage: sectest
include:
- template: Security/SAST.gitlab-ci.yml

run tests:
  stage: test
  image: docker
  services:
    - docker:dind    
  before_script:
    - apk add --update python py-pip python-dev && pip install docker-compose
    - docker version
    - docker-compose version
  script:
    - apk add --no-cache docker-compose
    - docker-compose build