# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=unotest
      - POSTGRES_DB=unoAPI
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 10s
        retries: 120
  api:
    env_file:
      - ./API/.devenv
    build: .
    volumes:
      - .:/unopad
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: